finance:
    resource: "@FinanceBundle/Controller/"
    type:     annotation
    prefix:   /

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /

closet:
    resource: "@ClosetBundle/Controller/"
    type:     annotation
    prefix:   /

food:
    resource: "@HealthBundle/Controller/"
    type:     annotation
    prefix:   /
